In [1]:
import numpy as np

In [2]:
array = np.array([5.7, 2.6, 3.5, 1.0])

In [3]:
array

array([5.7, 2.6, 3.5, 1. ])

In [4]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.full((2,2), "Numpy")

array([['Numpy', 'Numpy'],
       ['Numpy', 'Numpy']], dtype='<U5')

In [7]:
np.arange(0,1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [8]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.linspace(0.0,1.0, num=5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [10]:
np.random.rand(2,2)

array([[0.16586039, 0.08964644],
       [0.16799821, 0.94304271]])

In [11]:
np.random.randn(2,2)

array([[-0.05731365, -0.93614219],
       [-0.19047292,  0.61555249]])

In [12]:
np.random.randint(3,7, size=(2,4))

array([[4, 4, 4, 3],
       [3, 6, 5, 3]])

In [13]:
array = np.arange(2.0, 9.0)
print(array.dtype, array)

float64 [2. 3. 4. 5. 6. 7. 8.]


In [14]:
array = np.arange(1, 3, dtype= np.int64)
array.itemsize

8

In [15]:
array = np.arange(16)
print(array)
print("dimention of array:", array.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
dimention of array: 1


In [16]:
array.shape = (4,4)
print(array)
print("dimention of array:", array.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
dimention of array: 2


In [17]:
array.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
array1 = np.array([4, 6, 8, 9])
array2 = np.array([2, 3, 4, 5])
print("addition = ", array1 + array2)
print("sub = ",array1 - array2)
print("mul = ",array1 * array2)
print("div (float)= ",array1 / array2)
print("div (int) = ",array1 // array2)
print("square = ",array1 ** array2)


addition =  [ 6  9 12 14]
sub =  [2 3 4 4]
mul =  [ 8 18 32 45]
div (float)=  [2.  2.  2.  1.8]
div (int) =  [2 2 2 1]
square =  [   16   216  4096 59049]


In [19]:
array = np.array([[1, 2.5, 6],[8, 20, 11]])
for i in (array.min,array.max, array.sum, array.prod, array.std, array.var):
    print(i.__name__, "=", i())

min = 1.0
max = 20.0
sum = 48.5
prod = 26400.0
std = 6.274396828027022
var = 39.36805555555556


In [20]:
for i in (np.abs, np.sqrt, np.ceil, np.isnan):
    print("\n", i.__name__)
    print(i(array))


 absolute
[[ 1.   2.5  6. ]
 [ 8.  20.  11. ]]

 sqrt
[[1.         1.58113883 2.44948974]
 [2.82842712 4.47213595 3.31662479]]

 ceil
[[ 1.  3.  6.]
 [ 8. 20. 11.]]

 isnan
[[False False False]
 [False False False]]


In [21]:
array= np.array([5, 12, 4, -2, 15, 6, 8, 0])

In [22]:
array[4]

15

In [23]:
array[1:5]

array([12,  4, -2, 15])

In [24]:
array[3:-1]

array([-2, 15,  6,  8])

In [25]:
array[:4]

array([ 5, 12,  4, -2])

In [26]:
array[1::2]

array([12, -2,  6,  0])

In [27]:
array[::-1]

array([ 0,  8,  6, 15, -2,  4, 12,  5])

In [28]:
array[2:4]=11
array

array([ 5, 12, 11, 11, 15,  6,  8,  0])

In [29]:
array= np.array([5, 12, 4, -2, 15, 6, 8, 0])

In [30]:
newArray = array[2:4]
newArray

array([ 4, -2])

In [31]:
array[2]=200
newArray

array([200,  -2])

In [32]:
array= np.array([5, 12, 4, -2, 15, 6, 8, 0])

In [33]:
newArray =array[2:4].copy()
newArray

array([ 4, -2])

In [34]:
array[2]=200
newArray

array([ 4, -2])

In [35]:
array = np.arange(12)
array.shape=(3,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
array[2,3]

11

In [37]:
array[0,:]

array([0, 1, 2, 3])

In [38]:
array[:,2]

array([ 2,  6, 10])

In [39]:
array[:, (0,2)]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [40]:
array[(0,1),1:3]

array([[1, 2],
       [5, 6]])

In [41]:
array= np.arange(12)
array.shape=(3,2,2)
array

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [42]:
array[1,1,0]

6

In [43]:
array[1, : ,0]

array([4, 6])

In [44]:
array1 = np.full((2,4), 0.0)
array2 = np.full((3,4), 1.0)
array3 = np.full((4,4), 2.0)
print(array1)
print("\n",array2)
print("\n",array3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [45]:
array4= np.concatenate((array1, array2, array3), axis= 0)
array4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [46]:
array1 = np.full((2,4), 0.0)
array2 = np.full((2,4), 1.0)

print(array1)
print("\n",array2)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [47]:
array4= np.concatenate((array1, array2), axis= 1)
array4

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])